version: '3.8'

services:
  db:
    image: "postgres:15.1"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ~/volumes/pricehub:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
