version: '3.8'

services:
  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ~/volumes/media:/www/media
      - ./static:/www/static
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - back

  back:
    build:
      context: .
      target: django
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ~/volumes/media:/app/media
    environment:
      - DB_HOST=db
      - DEBUG=False
    depends_on:
      - db

  db:
    image: "postgres:15.1"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ~/volumes/pricehub:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pricehub
      - POSTGRES_PASSWORD=postgres
