version: '3.8'

services:
  scrapy:
    build:
      context: prchb
    volumes:
      - ./:/app

  db:
    image: "postgres:15.1"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ~/volumes/pricehub:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pricehub
      - POSTGRES_PASSWORD=postgres
