version: '3.8'

services:
  back:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: "postgres:15.1"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ~/volumes/pricehub:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pricehub
      - POSTGRES_PASSWORD=postgres
