# Generated by Django 4.1.7 on 2023-05-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesmodel',
            name='photo',
        ),
    ]
