# Generated by Django 4.1.7 on 2023-03-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='new_field',
            field=models.CharField(default='hello', max_length=140),
        ),
    ]
