# Generated by Django 4.1.7 on 2023-03-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='new_field',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
