# Generated by Django 4.1.7 on 2023-05-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
