# Generated by Django 4.1.7 on 2023-05-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
