# Generated by Django 4.1.7 on 2023-05-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productmodel_sku_alter_productmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='photo',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
