# Generated by Django 4.1.7 on 2023-05-13 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_alter_productmodel_photo_alter_productmodel_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
