# Generated by Django 4.1.7 on 2023-05-16 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_productmodel_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesmodel',
            name='photo',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='users',
            field=models.ManyToManyField(related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
