# Generated by Django 4.1.7 on 2023-05-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productmodel_users'),
        ('products', '0008_categoriesmodel_photo_alter_productmodel_users'),
    ]

    operations = [
    ]
