# Generated by Django 4.1.7 on 2023-05-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='uzum_remote_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
