# Generated by Django 4.1.7 on 2023-05-30 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productmodel_uzum_remote_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.URLField()),
                ('large', models.URLField()),
                ('small', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productmodel')),
            ],
            options={
                'db_table': 'product_photos',
            },
        ),
    ]
