# Generated by Django 4.1.7 on 2023-06-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productphotomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
